language: java
sudo: false
script: mvn -f ./server/pom.xml -Pserver-distro clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN
jdk:
- oraclejdk8
addons:
  sonarqube: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
env:
  global:
  - secure: TLYwD3fGznXcBAINNARSDqfFDEYq4vdMuZj+xOTHL+XHEL0PhVLA9twzTr5AZwZEnQdGoNuRkDQkEgYGIaLy6iv31hZuaXg0/u9uoQXVfDi93b/giugne0GB+ZKelxrzOtqD/o/chtd0VCI+iTZ18jt//1CBViIXYYHB72dTgDtaN9/Txl66Gfm7Bp/J2b0EXys3K1D/Nbbyiq9WhHxrN7d47mJTWrBovjVywx/gksl+/V3B7bm00Jhu512vkE7nYdJEU/pRJ7T6OVwRZm1ahlJcj+eromilDTky5f0ygW8zu+FiJcPQsQGma2deNBH0WBt45ulHMJHMO729bCdBmy88jPitGaHufk6DY1/VUen3HWz0zPO+z/YLzDM3AxrzdEDaE3uJ8J8+2SpjiMcf65AwHWWaZzHHbnmJ5hf6qnvWEvtHx1V2zH2Rr4Fd78zqhdmY1SpxuXJOcd69fAozyFDDYEEkV/E1K/z0YVk2dEJeDCA4BuyWrJb6t8P15C+PvREv2ADWyruvssJ/liJeHSgaq5Whg22IRknX7Ym/LpJG3pcJdKDrbVcC8+a5yy5zmIV18mZMh0XEZaopt6Z7gVQp62S/zyCt3nPwAXBE7q82rgcLTnXjIPESpBzVm3qsQITt44LCLVMDXqs7Sgdqluufk6M6VQYbp0FMt9A6oFA=
deploy:
  provider: bintray
  file: "./server/descriptor.json"
  user: gorkem
  key:
    secure: e9bgz2HPEzbwLv6F5b+JW0164LZWH5SxOesf2lsvjOK0+flzrqDdHiwGdN+1ND0E1Qc4eLNmhbi1fYblfzzIcWgtXuW5nZ0wdz08WlR1NrlUZ+u85ol9/7PFdbZSWqgDcQ7JPjrJ+pNozy7bV9jbEq7XU2ziRJQgicoIxRYe+AoJoPD3YC9TIvMW6TwtArCgWZndaqvoq9JLJqVJ5zUGeocbygaEyZmItUNyhYMUUkuFrtGChAMHY074dC0KEza7nCwXhBwg4hC1CZ7nm89p4PFSwvVQY3/ZaQrwFUqNyg8J42/DPzjkSyyycv89ylZnoCzAY+S8S5nIj33LANwG3bEhQlKVqlgzQd80mb7EvOHccWOkj/8xLvRCsD4kVbfrUJM4JVDjPO+DEtSFq5ptOiY4zc0XEkeWFvstmRIVOvpukS76ZbF/AyTMvEDHHVNIC7mZhegTFOK2+RFMGXAx4A8Ry+RE59EL0qInQlMQ2+eCPmVcOolEzMDVjig5EvZLIfmEUPdROUL9vFenlGQ1vBwg2ZYSnzO8ENHbruoLl9rAYOtRFezTodVvqFvLSlQGoKW/DfSAq8sCBccG8XbmQC5RHCgmN9Hck3QGs6O+ovEOl162LSTgtTTwdG3HY5CT+rsvqvyHEZ+7aE5gUd4yQESDZAHrdsOmXIA3cHb+TGw=
